# Generated by Django 2.2.3 on 2019-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashdrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('position', models.IntegerField()),
                ('delivery_location', models.CharField(max_length=250)),
                ('delivered_to', models.CharField(max_length=250)),
                ('date_of_delivery', models.DateField()),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('delivery_amount', models.IntegerField()),
                ('rate', models.CharField(choices=[('CHOOSE RATE', 'choose rate'), ('USD', 'usd'), ('SSP', 'ssp'), ('GBP', 'gbp'), ('UGX', 'ugx'), ('TSH', 'tsh')], default='choose rate', max_length=30)),
                ('delivery_agent', models.CharField(max_length=250)),
                ('sent_by', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Complete', 'complete')], default='Pending', max_length=30)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
