# Generated by Django 2.2.3 on 2019-07-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashdrops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdrop',
            name='position',
        ),
        migrations.AlterField(
            model_name='cashdrop',
            name='delivery_agent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='cashdrop',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Clients'),
        ),
        migrations.AlterField(
            model_name='cashdrop',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
