# Generated by Django 2.2.3 on 2019-07-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashdrops', '0002_auto_20190712_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashdrop',
            old_name='delivered_to',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='cashdrop',
            name='remarks',
        ),
    ]
