# Generated by Django 2.2.3 on 2019-07-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashdrops', '0003_auto_20190712_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrop',
            name='delivery_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.Agent'),
        ),
    ]
