# Generated by Django 2.2.3 on 2019-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashdrops', '0004_auto_20190712_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdrop',
            name='receiver_phone',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashdrop',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Complete', 'complete'), ('Cancelled', 'cancelled')], default='Pending', max_length=30),
        ),
    ]
