# Generated by Django 2.2.3 on 2019-07-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashdrops', '0005_auto_20190713_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashdrop',
            old_name='delivery_agent',
            new_name='delivery_personnel',
        ),
    ]
