# Generated by Django 2.2.3 on 2019-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20190712_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_personal',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
