# Generated by Django 2.2.3 on 2019-07-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_agent_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_personal',
            new_name='agent_personnel',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='agent_location',
            new_name='agent_personnel_location',
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(choices=[('SWEET', 'Sweet'), ('NUBA', 'Nuba')], default='Sweet', max_length=30),
        ),
    ]
