# Generated by Django 2.2.3 on 2019-07-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_client_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client_personal',
            new_name='client_personnel',
        ),
    ]
